---
- name: Install nginx
  shell: |
        ./configure --prefix=/etc/nginx \
            --sbin-path='{{ nginx_bin_path }}' \
            --modules-path=/usr/lib64/nginx/modules \
            --conf-path='{{ nginx_conf_path }}' \
            --error-log-path='{{ nginx_log_dir }}'/error.log \
            --pid-path=/var/run/nginx.pid \
            --lock-path=/var/run/nginx.lock \
            --user='{{nginx_user}}' \
            --group='{{nginx_group}}' \
            --build=CentOS \
            --builddir=nginx-{{ nginx_version }} \
            --with-select_module \
            --with-poll_module \
            --with-threads \
            --with-file-aio \
            --with-http_ssl_module \
            --with-http_v2_module \
            --with-http_realip_module \
            --with-http_addition_module \
            --with-http_xslt_module=dynamic \
            --with-http_image_filter_module=dynamic \
            --with-http_geoip_module=dynamic \
            --with-http_sub_module \
            --with-http_dav_module \
            --with-http_flv_module \
            --with-http_mp4_module \
            --with-http_gunzip_module \
            --with-http_gzip_static_module \
            --with-http_auth_request_module \
            --with-http_random_index_module \
            --with-http_secure_link_module \
            --with-http_degradation_module \
            --with-http_slice_module \
            --with-http_stub_status_module \
            --http-log-path='{{ nginx_log_dir }}'/access.log \
            --http-client-body-temp-path=/var/cache/nginx/client_temp \
            --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
            --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
            --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
            --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
            --with-mail=dynamic \
            --with-mail_ssl_module \
            --with-stream=dynamic \
            --with-stream_ssl_module \
            --with-stream_realip_module \
            --with-stream_geoip_module=dynamic \
            --with-stream_ssl_preread_module \
            --with-compat \
            --with-pcre={{download_path}}/pcre-{{pcre_version}} \
            --with-pcre-jit \
            --with-zlib=.{{download_path}}/zlib-{{ zlib_version}} \
            --with-openssl={{download_path}}/openssl-{{ openssl_version}} \
            --add-module={{ download_path }}/headers-more-nginx-module \
            --with-openssl-opt=no-nextprotoneg \
            --with-debug
  args:
       chdir: '{{ download_path}}/nginx-{{ nginx_version }}'