---

- name: Configure Systemd Service for Nginx
  template:
     src: debian-nginx-systemd.service.j2
     dest: /etc/systemd/system/nginx.service

- name: restart service nginx on Ubuntu, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx